In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing,metrics,pipeline,model_selection,ensemble
from sklearn_pandas import DataFrameMapper

In [2]:
df=pd.read_csv("Desktop/mpg_data_example.csv")

In [3]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino

In [4]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model year      origin  
count    398.000000  398.000000  398.000000  
mean      15.568090   76.010050    1.572864  
std        2.757689    3.697627    0.802055  
min        8.000000   70.000000    1.000000  
25%       13.825000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.175000   79.000000    2.000000  
max       24.800000   82.000000    3.000000

In [5]:
df['origin'].unique()

array([1, 3, 2], dtype=int64)

In [53]:
df['cylinders'].unique()

array([8, 4, 6, 3, 5], dtype=int64)

In [54]:
len(df['horsepower'].unique())

94

In [55]:
len(df['displacement'].unique())

82

In [56]:
len(df['weight'].unique())

351

In [57]:
len(df['acceleration'].unique())

95

In [58]:
len(df['mpg'].unique())

129

In [59]:
df['model year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], dtype=int64)

In [60]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [63]:
mapper=DataFrameMapper([
    (['cylinders', 'displacement', 'weight','acceleration', 'model year'],preprocessing.StandardScaler()),
    
    (['origin'],preprocessing.OneHotEncoder(handle_unknown='ignore'))
])

In [64]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [65]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [66]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [67]:
pipeline_obj=pipeline.Pipeline(
[('mapper',mapper),
('model',ensemble.RandomForestRegressor())])

In [68]:
X=[ 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin']
y=['mpg']

In [69]:
pipeline_obj.fit(df[X],df[y])

C:\Users\278\anaconda3\lib\site-packages\sklearn\pipeline.py:346: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)


Pipeline(steps=[('mapper',
                 DataFrameMapper(drop_cols=[],
                                 features=[(['cylinders', 'displacement',
                                             'weight', 'acceleration',
                                             'model year'],
                                            StandardScaler()),
                                           (['origin'],
                                            OneHotEncoder(handle_unknown='ignore'))])),
                ('model', RandomForestRegressor())])

In [70]:
pipeline_obj.predict(df[X])

array([17.272, 14.72 , 17.34 , 16.557, 16.911, 14.52 , 13.71 , 14.26 ,
       13.13 , 14.82 , 14.96 , 14.44 , 14.94 , 15.288, 24.   , 21.078,
       19.272, 20.763, 26.99 , 26.76 , 24.35 , 24.347, 24.78 , 25.165,
       20.798, 10.63 , 10.875, 11.71 ,  9.88 , 27.03 , 26.575, 24.502,
       26.245, 19.808, 16.798, 17.441, 18.7  , 18.321, 14.01 , 13.53 ,
       14.15 , 14.05 , 12.24 , 12.81 , 12.65 , 18.75 , 21.696, 18.811,
       18.5  , 23.424, 27.12 , 29.63 , 29.255, 31.2  , 33.71 , 27.49 ,
       27.   , 24.774, 25.905, 23.21 , 20.566, 21.965, 13.6  , 13.6  ,
       14.54 , 14.115, 16.115, 11.67 , 12.85 , 12.38 , 13.135, 20.69 ,
       14.92 , 13.4  , 13.25 , 14.02 , 19.27 , 22.072, 20.62 , 26.18 ,
       22.427, 26.565, 22.906, 27.08 , 26.87 , 13.51 , 14.635, 13.475,
       14.02 , 14.65 , 11.99 , 13.175, 13.195, 14.04 , 12.48 , 12.02 ,
       13.335, 18.478, 16.365, 18.272, 17.823, 21.87 , 26.493, 11.42 ,
       12.18 , 12.85 , 12.545, 18.5  , 22.23 , 20.816, 22.94 , 22.81 ,
      

In [71]:
import sklearn.externals

In [72]:
import joblib

In [73]:
joblib.dump(pipeline_obj,'RFCar.pkl')

['RFCar.pkl']

In [74]:
kd=joblib.load('RFCar.pkl')

In [75]:
kd.predict(df[X])

array([17.272, 14.72 , 17.34 , 16.557, 16.911, 14.52 , 13.71 , 14.26 ,
       13.13 , 14.82 , 14.96 , 14.44 , 14.94 , 15.288, 24.   , 21.078,
       19.272, 20.763, 26.99 , 26.76 , 24.35 , 24.347, 24.78 , 25.165,
       20.798, 10.63 , 10.875, 11.71 ,  9.88 , 27.03 , 26.575, 24.502,
       26.245, 19.808, 16.798, 17.441, 18.7  , 18.321, 14.01 , 13.53 ,
       14.15 , 14.05 , 12.24 , 12.81 , 12.65 , 18.75 , 21.696, 18.811,
       18.5  , 23.424, 27.12 , 29.63 , 29.255, 31.2  , 33.71 , 27.49 ,
       27.   , 24.774, 25.905, 23.21 , 20.566, 21.965, 13.6  , 13.6  ,
       14.54 , 14.115, 16.115, 11.67 , 12.85 , 12.38 , 13.135, 20.69 ,
       14.92 , 13.4  , 13.25 , 14.02 , 19.27 , 22.072, 20.62 , 26.18 ,
       22.427, 26.565, 22.906, 27.08 , 26.87 , 13.51 , 14.635, 13.475,
       14.02 , 14.65 , 11.99 , 13.175, 13.195, 14.04 , 12.48 , 12.02 ,
       13.335, 18.478, 16.365, 18.272, 17.823, 21.87 , 26.493, 11.42 ,
       12.18 , 12.85 , 12.545, 18.5  , 22.23 , 20.816, 22.94 , 22.81 ,
      

In [76]:
temp={}
temp['cylinders']=1
temp['displacement']=2
temp['horsepower'] = 3
temp['weight']=4
temp['acceleration'] =5
temp['model year']=6
temp['origin'] =1



In [77]:
testData=pd.DataFrame({'x':temp}).transpose()

In [78]:
testData

acceleration  cylinders  displacement  horsepower  model year  origin  \
x             5          1             2           3           6       1   

   weight  
x       4

In [79]:
kd.predict(testData)[0]

29.083